#!/bin/sh
#
# This software is in the public domain, furnished "as is", without technical
# support, and with no warranty, express or implied, as to its usefulness for
# any purpose.
#
# Author: Iuri Diniz <iuridiniz --at-- gmail.com>

#PATH=/bin:/usr/bin:/usr/local/bin

BASEDIR=$( (cd -P "`dirname "$0"`" && pwd) )

NAME=$( basename $0 )

# adds $SRC/bin if exists
if [ -d "$BASEDIR/bin" ]; then
  PATH=$BASEDIR/bin:$PATH
fi

DRG2BIN=$( which drg2sbg )
SBAGEN=$( which sbagen )
PLAY=$( which play )
SOX=$( which sox )

CONVERT=0
ERROR=0

usage() {
    echo \
         "Usage:\n" \
         "\$ drgplay <inputfile>\n"\
         "\$ drgconvert <inputfile> <output>\n"\
         "\n"\
         "For complete usage, requirements and howto see manual page:\n"\
         "\$ man $NAME\n"\
         "\n"\
         "Or access this url:"\
         "https://github.com/iuridiniz/drg-play/blob/master/README.rst"
}

if [ "$NAME" = "drgconvert" ]; then
    CONVERT=1
fi

if [ ! -x "$DRG2BIN" ]; then
    echo '** Cannot find the required program ``drg2bin``'
fi

if [ ! -x "$SBAGEN" ]; then
    echo '** Cannot find the required program ``sbagen``'
    ERROR=1
fi

if [ ! -x "$PLAY" ]; then
    echo '** Cannot find the required program ``play`` (provided by SOX)'
    ERROR=1
fi

if [ ! -x "$SOX" ]; then
    echo '** Cannot find the required program ``sox`'
    ERROR=1
fi

if [ -z "$1" ]; then
    ERROR=1
fi

if [ "x$CONVERT" = "x1" -a -z "$2" ]; then
    ERROR=1
fi


if [ "x$ERROR" != "x0" ]; then
    usage
    exit $ERROR
fi

FILE="$1"
OUTPUT="$2"

SAMPLE_RATE="44100"
SAMPLE_BITS="16"

DRG2BIN_OPTS=""
SBAGEN_OPTS="-Q -r $SAMPLE_RATE -b $SAMPLE_BITS -O"
SOX_OPTS="-q -t raw -s -r $SAMPLE_RATE -b $SAMPLE_BITS"

if [ "x$CONVERT" = "x1" ]; then

    if [ "x$OUTPUT" = "x-" ]; then
        "$DRG2BIN" $DRG2BIN_OPTS "$FILE" | \
        "$SBAGEN" $SBAGEN_OPTS -
    else
        "$DRG2BIN" $DRG2BIN_OPTS "$FILE" | \
        "$SBAGEN" $SBAGEN_OPTS - | \
            "$SOX" $SOX_OPTS - "$OUTPUT"
    fi
    exit $?
fi

"$DRG2BIN" $DRG2BIN_OPTS "$FILE" | \
    "$SBAGEN" $SBAGEN_OPTS - | \
    "$PLAY" $SOX_OPTS -

exit $?
